from .caption import CaptionTask
from .image_gen import ImageGenTask
from .refcoco import RefcocoTask
from .snli_ve import SnliVeTask
from .vqa_gen import VqaGenTask
from .vqa_gen_x import VqaGenXTask
from .e_snli_ve import ESnliVeTask
from .vcr import VCRTask
from .vcr_baseline import VCRBaseTask
from .unify_explanation import UnifyExplanationTask
